const COMPETITION_STATUS = {
  UPCOMING: 'UPCOMING',
  REGISTRATION_OPEN: 'REGISTRATION_OPEN',
  FULL: 'FULL',
  LIVE: 'LIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const PARTICIPATION_STATUS = {
  REGISTERED: 'REGISTERED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED'
};

module.exports = {
  COMPETITION_STATUS,
  PARTICIPATION_STATUS
};
